import { VisualizationMode } from './base.js'
import { pitchTempoToRGB } from '../palette.js'

// Audio Tetris - Pieces generated by music
// Bass = heavy blocks, High = light pieces, Tempo = speed
export class TetrisMode extends VisualizationMode {
  constructor(ctx, width, height) {
    super(ctx, width, height)
    this.name = 'tetris'
    this.description = 'Tetris where pieces are chosen by audio. Bass = heavy, highs = light.'

    // Grid settings
    this.cols = 10
    this.rows = 20
    this.cellSize = Math.min(
      Math.floor((height * 0.85) / this.rows),
      Math.floor((width * 0.4) / this.cols)
    )

    // Center the grid
    this.gridX = (width - this.cols * this.cellSize) / 2
    this.gridY = (height - this.rows * this.cellSize) / 2

    // Game state
    this.grid = []
    this.currentPiece = null
    this.nextPiece = null
    this.score = 0
    this.lines = 0
    this.level = 1
    this.gameOver = false

    // Timing
    this.dropTimer = 0
    this.baseDropInterval = 1000
    this.dropInterval = this.baseDropInterval
    this.lastBeat = 0

    // Audio influence
    this.smoothBass = 0
    this.smoothMid = 0
    this.smoothHigh = 0
    this.smoothAmplitude = 0
    this.currentHue = 0

    // Tetromino definitions
    this.tetrominoes = {
      I: { shape: [[1,1,1,1]], color: '#00f0f0', weight: 'light' },
      O: { shape: [[1,1],[1,1]], color: '#f0f000', weight: 'heavy' },
      T: { shape: [[0,1,0],[1,1,1]], color: '#a000f0', weight: 'medium' },
      S: { shape: [[0,1,1],[1,1,0]], color: '#00f000', weight: 'light' },
      Z: { shape: [[1,1,0],[0,1,1]], color: '#f00000', weight: 'light' },
      J: { shape: [[1,0,0],[1,1,1]], color: '#0000f0', weight: 'heavy' },
      L: { shape: [[0,0,1],[1,1,1]], color: '#f0a000', weight: 'heavy' }
    }

    this.pieceTypes = Object.keys(this.tetrominoes)
    this.heavyPieces = ['O', 'J', 'L', 'T']
    this.lightPieces = ['I', 'S', 'Z']

    // Input
    this.setupInput()
  }

  setupInput() {
    this.keyHandler = (e) => {
      if (this.gameOver) {
        if (e.key === ' ' || e.key === 'Enter') {
          this.init()
        }
        return
      }

      if (!this.currentPiece) return

      switch (e.key) {
        case 'ArrowLeft':
        case 'a':
        case 'A':
          this.movePiece(-1, 0)
          break
        case 'ArrowRight':
        case 'd':
        case 'D':
          this.movePiece(1, 0)
          break
        case 'ArrowDown':
        case 's':
        case 'S':
          this.movePiece(0, 1)
          break
        case 'ArrowUp':
        case 'w':
        case 'W':
          this.rotatePiece()
          break
        case ' ':
          this.hardDrop()
          break
      }
    }
    window.addEventListener('keydown', this.keyHandler)
  }

  init() {
    // Initialize grid
    this.grid = Array(this.rows).fill(null).map(() => Array(this.cols).fill(null))
    this.score = 0
    this.lines = 0
    this.level = 1
    this.gameOver = false
    this.dropTimer = 0

    // Spawn first pieces
    this.nextPiece = this.createPiece(this.randomPieceType())
    this.spawnPiece()
  }

  randomPieceType() {
    return this.pieceTypes[Math.floor(Math.random() * this.pieceTypes.length)]
  }

  audioPieceType() {
    // Choose piece based on audio characteristics
    if (this.smoothBass > 0.6 && this.smoothBass > this.smoothHigh) {
      // Heavy bass = heavy pieces
      return this.heavyPieces[Math.floor(Math.random() * this.heavyPieces.length)]
    } else if (this.smoothHigh > 0.5 && this.smoothHigh > this.smoothBass) {
      // High frequencies = light pieces
      return this.lightPieces[Math.floor(Math.random() * this.lightPieces.length)]
    } else {
      // Balanced = any piece
      return this.randomPieceType()
    }
  }

  createPiece(type) {
    const tetro = this.tetrominoes[type]
    return {
      type,
      shape: tetro.shape.map(row => [...row]),
      color: tetro.color,
      x: Math.floor((this.cols - tetro.shape[0].length) / 2),
      y: 0,
      hue: this.currentHue
    }
  }

  spawnPiece() {
    this.currentPiece = this.nextPiece
    this.nextPiece = this.createPiece(this.audioPieceType())

    // Check if spawn position is blocked (game over)
    if (this.checkCollision(this.currentPiece.x, this.currentPiece.y, this.currentPiece.shape)) {
      this.gameOver = true
    }
  }

  movePiece(dx, dy) {
    if (!this.currentPiece) return false

    const newX = this.currentPiece.x + dx
    const newY = this.currentPiece.y + dy

    if (!this.checkCollision(newX, newY, this.currentPiece.shape)) {
      this.currentPiece.x = newX
      this.currentPiece.y = newY
      return true
    }

    // If moving down and collision, lock piece
    if (dy > 0) {
      this.lockPiece()
    }

    return false
  }

  rotatePiece() {
    if (!this.currentPiece) return

    const rotated = this.rotateMatrix(this.currentPiece.shape)

    // Try rotation, with wall kicks
    const kicks = [0, -1, 1, -2, 2]
    for (const kick of kicks) {
      if (!this.checkCollision(this.currentPiece.x + kick, this.currentPiece.y, rotated)) {
        this.currentPiece.shape = rotated
        this.currentPiece.x += kick
        return
      }
    }
  }

  rotateMatrix(matrix) {
    const rows = matrix.length
    const cols = matrix[0].length
    const rotated = Array(cols).fill(null).map(() => Array(rows).fill(0))

    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        rotated[c][rows - 1 - r] = matrix[r][c]
      }
    }

    return rotated
  }

  hardDrop() {
    if (!this.currentPiece) return

    while (this.movePiece(0, 1)) {
      this.score += 2
    }
  }

  checkCollision(x, y, shape) {
    for (let r = 0; r < shape.length; r++) {
      for (let c = 0; c < shape[r].length; c++) {
        if (shape[r][c]) {
          const newX = x + c
          const newY = y + r

          // Check bounds
          if (newX < 0 || newX >= this.cols || newY >= this.rows) {
            return true
          }

          // Check grid collision (only if within grid)
          if (newY >= 0 && this.grid[newY][newX]) {
            return true
          }
        }
      }
    }
    return false
  }

  lockPiece() {
    if (!this.currentPiece) return

    // Add piece to grid
    for (let r = 0; r < this.currentPiece.shape.length; r++) {
      for (let c = 0; c < this.currentPiece.shape[r].length; c++) {
        if (this.currentPiece.shape[r][c]) {
          const gridY = this.currentPiece.y + r
          const gridX = this.currentPiece.x + c

          if (gridY >= 0 && gridY < this.rows && gridX >= 0 && gridX < this.cols) {
            this.grid[gridY][gridX] = {
              color: this.currentPiece.color,
              hue: this.currentPiece.hue
            }
          }
        }
      }
    }

    // Check for completed lines
    this.clearLines()

    // Spawn next piece
    this.spawnPiece()
  }

  clearLines() {
    let linesCleared = 0

    for (let r = this.rows - 1; r >= 0; r--) {
      if (this.grid[r].every(cell => cell !== null)) {
        // Remove line
        this.grid.splice(r, 1)
        // Add empty line at top
        this.grid.unshift(Array(this.cols).fill(null))
        linesCleared++
        r++ // Check same row again
      }
    }

    if (linesCleared > 0) {
      this.lines += linesCleared
      // Scoring: 1=100, 2=300, 3=500, 4=800
      const points = [0, 100, 300, 500, 800][linesCleared] || 800
      this.score += points * this.level

      // Level up every 10 lines
      this.level = Math.floor(this.lines / 10) + 1
    }
  }

  update(audioFeatures, beatInfo) {
    if (this.gameOver) return

    const { amplitude, centroid, bass, mid, high } = audioFeatures
    const { onBeat, beatIntensity, normalizedTempo } = beatInfo

    // Smooth audio
    const smoothing = 0.15
    this.smoothBass += (bass - this.smoothBass) * smoothing
    this.smoothMid += (mid - this.smoothMid) * smoothing
    this.smoothHigh += (high - this.smoothHigh) * smoothing
    this.smoothAmplitude += (amplitude - this.smoothAmplitude) * smoothing

    // Current hue from pitch
    this.currentHue = centroid * 360

    // Drop speed influenced by tempo
    const tempoMultiplier = 0.3 + normalizedTempo * 1.4
    this.dropInterval = this.baseDropInterval / (this.level * 0.5 + 0.5) / tempoMultiplier

    // Update drop timer
    this.dropTimer += 16 // Approximate frame time

    // Beat = instant drop one row
    if (onBeat && beatIntensity > 0.5) {
      this.movePiece(0, 1)
      this.dropTimer = 0
    }

    // Normal drop
    if (this.dropTimer >= this.dropInterval) {
      this.movePiece(0, 1)
      this.dropTimer = 0
    }
  }

  draw() {
    // Draw grid background
    this.ctx.fillStyle = 'rgba(20, 20, 30, 0.9)'
    this.ctx.fillRect(
      this.gridX - 5,
      this.gridY - 5,
      this.cols * this.cellSize + 10,
      this.rows * this.cellSize + 10
    )

    // Draw grid lines
    this.ctx.strokeStyle = 'rgba(60, 60, 80, 0.5)'
    this.ctx.lineWidth = 1

    for (let c = 0; c <= this.cols; c++) {
      this.ctx.beginPath()
      this.ctx.moveTo(this.gridX + c * this.cellSize, this.gridY)
      this.ctx.lineTo(this.gridX + c * this.cellSize, this.gridY + this.rows * this.cellSize)
      this.ctx.stroke()
    }

    for (let r = 0; r <= this.rows; r++) {
      this.ctx.beginPath()
      this.ctx.moveTo(this.gridX, this.gridY + r * this.cellSize)
      this.ctx.lineTo(this.gridX + this.cols * this.cellSize, this.gridY + r * this.cellSize)
      this.ctx.stroke()
    }

    // Draw locked pieces
    for (let r = 0; r < this.rows; r++) {
      for (let c = 0; c < this.cols; c++) {
        if (this.grid[r][c]) {
          this.drawCell(c, r, this.grid[r][c].color, this.grid[r][c].hue)
        }
      }
    }

    // Draw ghost piece (preview of where piece will land)
    if (this.currentPiece && !this.gameOver) {
      let ghostY = this.currentPiece.y
      while (!this.checkCollision(this.currentPiece.x, ghostY + 1, this.currentPiece.shape)) {
        ghostY++
      }

      this.ctx.globalAlpha = 0.3
      for (let r = 0; r < this.currentPiece.shape.length; r++) {
        for (let c = 0; c < this.currentPiece.shape[r].length; c++) {
          if (this.currentPiece.shape[r][c]) {
            this.drawCell(
              this.currentPiece.x + c,
              ghostY + r,
              this.currentPiece.color,
              this.currentPiece.hue
            )
          }
        }
      }
      this.ctx.globalAlpha = 1
    }

    // Draw current piece
    if (this.currentPiece && !this.gameOver) {
      for (let r = 0; r < this.currentPiece.shape.length; r++) {
        for (let c = 0; c < this.currentPiece.shape[r].length; c++) {
          if (this.currentPiece.shape[r][c]) {
            this.drawCell(
              this.currentPiece.x + c,
              this.currentPiece.y + r,
              this.currentPiece.color,
              this.currentPiece.hue
            )
          }
        }
      }
    }

    // Draw next piece preview
    this.drawNextPiece()

    // Draw score/info
    this.drawUI()

    // Game over overlay
    if (this.gameOver) {
      this.ctx.fillStyle = 'rgba(0, 0, 0, 0.7)'
      this.ctx.fillRect(0, 0, this.width, this.height)

      this.ctx.fillStyle = '#fff'
      this.ctx.font = 'bold 48px "SF Mono", Monaco, monospace'
      this.ctx.textAlign = 'center'
      this.ctx.fillText('GAME OVER', this.width / 2, this.height / 2 - 40)

      this.ctx.font = '24px "SF Mono", Monaco, monospace'
      this.ctx.fillText(`Score: ${this.score}`, this.width / 2, this.height / 2 + 20)
      this.ctx.fillText(`Lines: ${this.lines}`, this.width / 2, this.height / 2 + 50)

      this.ctx.font = '16px "SF Mono", Monaco, monospace'
      this.ctx.fillStyle = '#888'
      this.ctx.fillText('Press SPACE to restart', this.width / 2, this.height / 2 + 100)

      this.ctx.textAlign = 'left'
    }
  }

  drawCell(col, row, color, hue = 0) {
    const x = this.gridX + col * this.cellSize
    const y = this.gridY + row * this.cellSize
    const size = this.cellSize - 2

    // Glow effect based on audio
    const glowSize = this.smoothAmplitude * 10

    if (glowSize > 2) {
      this.ctx.shadowColor = `hsl(${hue}, 80%, 50%)`
      this.ctx.shadowBlur = glowSize
    }

    // Fill with audio-tinted color
    const baseColor = color
    this.ctx.fillStyle = baseColor
    this.ctx.fillRect(x + 1, y + 1, size, size)

    // Highlight
    this.ctx.fillStyle = 'rgba(255, 255, 255, 0.3)'
    this.ctx.fillRect(x + 1, y + 1, size, 3)
    this.ctx.fillRect(x + 1, y + 1, 3, size)

    // Shadow
    this.ctx.fillStyle = 'rgba(0, 0, 0, 0.3)'
    this.ctx.fillRect(x + 1, y + size - 2, size, 2)
    this.ctx.fillRect(x + size - 2, y + 1, 2, size)

    this.ctx.shadowBlur = 0
  }

  drawNextPiece() {
    if (!this.nextPiece) return

    const previewX = this.gridX + this.cols * this.cellSize + 30
    const previewY = this.gridY + 30

    this.ctx.fillStyle = '#888'
    this.ctx.font = '14px "SF Mono", Monaco, monospace'
    this.ctx.fillText('NEXT', previewX, previewY - 10)

    this.ctx.fillStyle = 'rgba(30, 30, 40, 0.8)'
    this.ctx.fillRect(previewX, previewY, this.cellSize * 4 + 10, this.cellSize * 4 + 10)

    const offsetX = (4 - this.nextPiece.shape[0].length) / 2
    const offsetY = (4 - this.nextPiece.shape.length) / 2

    for (let r = 0; r < this.nextPiece.shape.length; r++) {
      for (let c = 0; c < this.nextPiece.shape[r].length; c++) {
        if (this.nextPiece.shape[r][c]) {
          const x = previewX + 5 + (c + offsetX) * this.cellSize
          const y = previewY + 5 + (r + offsetY) * this.cellSize

          this.ctx.fillStyle = this.nextPiece.color
          this.ctx.fillRect(x, y, this.cellSize - 2, this.cellSize - 2)
        }
      }
    }
  }

  drawUI() {
    const uiX = this.gridX + this.cols * this.cellSize + 30
    let uiY = this.gridY + 150

    this.ctx.fillStyle = '#fff'
    this.ctx.font = '14px "SF Mono", Monaco, monospace'

    this.ctx.fillText(`Score: ${this.score}`, uiX, uiY)
    uiY += 25
    this.ctx.fillText(`Lines: ${this.lines}`, uiX, uiY)
    uiY += 25
    this.ctx.fillText(`Level: ${this.level}`, uiX, uiY)

    // Audio influence indicator
    uiY += 40
    this.ctx.fillStyle = '#666'
    this.ctx.fillText('Audio:', uiX, uiY)
    uiY += 20

    // Bass bar
    this.ctx.fillStyle = '#444'
    this.ctx.fillRect(uiX, uiY, 100, 10)
    this.ctx.fillStyle = '#f44'
    this.ctx.fillRect(uiX, uiY, this.smoothBass * 100, 10)
    this.ctx.fillStyle = '#888'
    this.ctx.fillText('Bass', uiX + 110, uiY + 10)
    uiY += 20

    // High bar
    this.ctx.fillStyle = '#444'
    this.ctx.fillRect(uiX, uiY, 100, 10)
    this.ctx.fillStyle = '#4af'
    this.ctx.fillRect(uiX, uiY, this.smoothHigh * 100, 10)
    this.ctx.fillStyle = '#888'
    this.ctx.fillText('High', uiX + 110, uiY + 10)

    // Controls hint
    const hintY = this.gridY + this.rows * this.cellSize - 80
    this.ctx.fillStyle = 'rgba(255, 255, 255, 0.3)'
    this.ctx.font = '12px "SF Mono", Monaco, monospace'
    this.ctx.fillText('← → Move', uiX, hintY)
    this.ctx.fillText('↑ Rotate', uiX, hintY + 18)
    this.ctx.fillText('↓ Soft drop', uiX, hintY + 36)
    this.ctx.fillText('Space: Hard drop', uiX, hintY + 54)
  }

  clear() {
    this.init()
  }

  dispose() {
    window.removeEventListener('keydown', this.keyHandler)
  }
}
